### ISSUE TITLE
Baritone Does Not Work

### ISSUE THREAD

**Issue by fatihturan** [tma02/baritone#1]
Hi,

I launched the Baritone but it seems Baritone can not communicate with Spotify: http://jmp.sh/J6ue52Y I restarted Spotify and Baritone and it does not solve my problem.

[My Spotify version is 1.0.28.87.g8f9312a4](http://jmp.sh/HXL8s4U) and I am using OS X 10.11.4.

So what is wrong with it?

**Comment by tma02** [comment]
At this point I suspect it's because the Web Helper had its default port taken by another process. Could you check what process is listening on port 4370?

**Comment by fatihturan** [comment]
I can not find any process with 4370 but Spotify listening on 4371, 4381 and 57621.

**Comment by tma02** [comment]
Okay I will need to write some port detection tonight. Cheers!

**Comment by tma02** [comment]
Try out the latest release and let me know if anything changes for you.

**Comment by fatihturan** [comment]
It's currently working. Thank you. :)
