### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by Revod** [tma02/baritone#11]
Just keep getting this:

![screen shot 2017-05-30 at 1 08 28 am](https://cloud.githubusercontent.com/assets/10109689/26568820/8078f00a-44d4-11e7-8682-e44129095a92.png)

**Comment by tma02** [comment]
This could have something to do with a recent API change which now requires an OAuth token for an endpoint that was previously unauthenticated. I will be writing an update to support the new API soon.

**Comment by FlorianH** [comment]
I have the same problem.

Thank you so much for looking into this @tma02.<3

**Comment by Revod** [comment]
Thank you @tma02

**Comment by mikdale** [comment]
I'm having the same issue. Any update would be much appreciated!

**Comment by tma02** [comment]
This issue should be fixed in the latest commit b5aaaa2

**Comment by Revod** [comment]
Thank you

**Comment by FlorianH** [comment]
Thank you so much!
