### ISSUE TITLE
Preferences grayed out

### ISSUE THREAD

**Issue by lukeramsden** [tma02/baritone#4]

**Comment by tma02** [comment]
A preferences window was in the works but context menu options for the preferences proved to be more elegant. The preferences window was never implemented. Removing the grayed out option entirely should prevent any further confusion.

**Comment by ghost** [comment]
Is it normal behavior for "smaller album art" to also be grayed out?

**Comment by tma02** [comment]
That option hasn't been implemented yet so yes

**Comment by ghost** [comment]
Alright, thanks for the reply. Love Baritone so far!

**Comment by tma02** [comment]
Fixed in 41f6817
