### ISSUE TITLE
Song Name, Artist Name, and Album Name when you click the button

### ISSUE THREAD

**Issue by MeetThePatel** [tma02/baritone#6]
Can you implement a feature where when you click the button, and the album cover shows, underneath it, it shows the Song name, Artist name, and Album name?

Thanks in advance!

**Comment by tma02** [comment]
Instead of the overlay that shows up when you hover over the album art?

**Comment by MeetThePatel** [comment]
Have it something like this, but fit it into your theme, because your theme looks better

![image](https://cloud.githubusercontent.com/assets/11304993/21668728/9937416a-d2d2-11e6-8557-5aa028d1f5a6.png)

**Comment by MeetThePatel** [comment]
Have the song info right above the music controls

**Comment by tma02** [comment]
I'm a little confused, Baritone already shows the song info when you hover over the album art. Are you looking for a different implementation to show the song info above the music controls?

**Comment by MeetThePatel** [comment]
Oh I am so sorry, I did not see the little thing that pops up when you hover above the album art. Im am going to close this issue, but also, so other people don't raise this issue, you should attach a GIF in the ready of this in use

**Comment by tma02** [comment]
No problem, and yeah that doesn't sound like a bad idea.
