### ISSUE TITLE
TypeError: Cannot read property 'album_resource' of undefined

### ISSUE THREAD

**Issue by andtos90** [tma02/baritone#8]
It's almost a week that Baritone is not working on my computer, but the Spotify client is fine. Just now I tried to run it on iTerm and i get this error:

`TypeError: Cannot read property 'album_resource' of undefined`

To give you more information I logged the _data_ variable inside _getCurrentAlbumId_ and i get:

`{ error: { type: '4102', message: 'Invalid OAuth token' },
  version: 9,
  client_version: '1.0.50.41368.gbd68dbef',
  running: true }`

The interesting part is that ouath is something similar to this:

`{ t: 'NAowAhgKG1Nwb3RpBhkSaBoGmAEByAEBJRkS1lUSFChLvW4mGdnft8WUvRyfaketoken' }`

I did not put the 'faketoken'  in the end, this is the real data parsed by the function _getJson_. It looks like is something broken with Spotify, have you ever encountered this problem?

P.S. great work, I really like to use Baritone

**Comment by tma02** [comment]
There was an update released to address this issue a few days ago, are you running the latest version? It should be 1.0.7

**Comment by andtos90** [comment]
You're right, I was running the 1.0.6 version. Thanks a lot!

**Comment by tma02** [comment]
It seems like this issue is resolved so I'll go ahead and close it.
